const constants = {
    LOGIN: "LOGIN",
    LOGIN_SUCCEDED: "LOGIN_SUCCEDED",
    LOGIN_FAILED: "LOGIN_FAILED",

    REGISTER: "REGISTER",
    REGISTER_SUCCEDED: "REGISTER_SUCCEDED",
    REGISTER_FAILED: "REGISTER_FAILED",
}

export default constants